version: '3'

tasks:
  build:
    cmds:
      - go build -o tranny .

  install:
    cmds:
      - go install .

  run:
    cmds:
      - go run . {{.CLI_ARGS}}

  lint:
    cmds:
      - go vet ./...

  uninstall:
    cmds:
      - rm -f $(go env GOPATH)/bin/tranny

  clean:
    cmds:
      - rm -f tranny
